MAS=../bin/mas

all:
	$(MAS) fibonacci.asm -o fibonacci
	$(MAS) par.asm -o par
	$(MAS) hello.asm -o hello
	$(MAS) suma.asm -o suma
	$(MAS) negativo.asm -o negativo

clean:
	rm -f fibonacci
	rm -f par
	rm -f hello
	rm -f suma
	rm -f negativo